[package]
name = "modula-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "modula"
path = "src/main.rs"

[dependencies]
modula-core.workspace = true
modula-services.workspace = true
modula-state.workspace = true
modula-grpc.workspace = true
modula-cli.workspace = true
modula-platform = { path = "../../crates/modula_platform" }
modula-plugin.workspace = true
modula-plugin-remote = { path = "../../plugins/remote" }
modula-engine-transport.workspace = true
anyhow.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
clap.workspace = true
tonic.workspace = true

[dev-dependencies]
tempfile.workspace = true
