[package]
name = "modula-state"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
modula-core.workspace = true
modula-services.workspace = true
modula-db.workspace = true
modula-plugin.workspace = true
modula-platform.workspace = true
modula-engine-transport.workspace = true
anyhow.workspace = true
tokio.workspace = true
tracing.workspace = true
